version: 0.0
os: linux	
files:	
  - source: /jewellery_management 
    destination: /odoo-custom-addons/    
hooks:	
  BeforeInstall:	 
    - location: scripts/install_dependencies	   
      timeout: 300	     
      runas: odoo -S
    - location: scripts/start_server	    
      timeout: 300	     
      runas: root	  
