version: 0.2
 
phases:
  install:
    commands:
      - pip3 install pycodestyle

  build:
    commands:
      - echo Build started on `date`
      - find . -name \*.py -exec pycodestyle --ignore=E402 {} +
      
      
   
artifacts:
  type: 
  files:
    - index.html
    - appspec.yml
    - scripts/install_dependencies
    - scripts/start_server
